/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
    ],
    theme: {
        extend: {
            colors: {
                "ngekos-black": "#070707",
                "ngekos-grey": "#5E6F76",
                "ngekos-orange": "#FF801A",
                "orange-main": "#EA580C",
                cancel: "#FF0000",
                primary: "#D81D76",
                secondary: "#AE1679",
                "custom-gray": "#424242",
                "custom-gray-10": "#FFFFFF",
                "custom-gray-20": "#F5F5F5",
                "custom-gray-30": "#EDEDED",
                "custom-gray-40": "#E0E0E0",
                "custom-gray-50": "#C2C2C2",
                "custom-gray-60": "#9E9E9E",
                "custom-gray-70": "#757575",
                "custom-gray-80": "#616161",
                "custom-gray-90": "#424242",
                "custom-gray-100": "#0A0A0A",
                "green-primary": "#439F21",
                "green-secondary": "#327719",
                "danger-main": "#B00020",
                "primary-border": "#F3BBD6",
                "primary-secondary": "#FBE8F1",
                "secondary-border": "#CCEEBF",
                "warning-main": "#F4DE1A",
                "warning-secondary": "#FDF8D1",
                "warning-pressed": "#928510",
                "danger-secondary": "#F7C3CD",
                "danger-pressed": "#8D001A",
                "danger-focus": "#FFD9E0",
                "success-main": "#1C7D44",
                "success-secondary": "#EAFAF1",
                "success-pressed": "#1C7D44",
                "success-focus": "#D5F6E3",
                "info-focus": "#CCD3F8",
            },
        },
    },
    plugins: [],
};
