name: 🚀 Deploy to cPanel via SFTP
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy Laravel Website
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        
      - name: 📦 Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          
      - name: 📦 Zip vendor folder
        run: |
          zip -r vendor.zip vendor
          rm -rf vendor
          
      - name: 📂 Sync files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: ./*
          remote_path: ./
          sftpArgs: '-o StrictHostKeyChecking=no'
