name: 🚀 Deploy to cPanel via FTP
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy Laravel Website
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        
      # Install dependencies via Composer
      - name: 📦 Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-dev --optimize-autoloader
          
      # Zip vendor folder untuk mempercepat upload
      - name: 📦 Zip vendor folder
        run: |
          zip -r vendor.zip vendor
          rm -rf vendor
          
      # Sync files via FTP
      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /home/wablitzc/public_html/wablitz.com/
          passive: true  # Gunakan mode pasif untuk mengatasi firewall
          exclude: |
            .git*
            node_modules
            .github
