name: 🚀 Deploy to cPanel via FTP

on:
  push:
    branches:
      - main  # Ganti dengan nama branch yang digunakan, seperti 'main' atau 'master'

jobs:
  web-deploy:
    name: 🎉 Deploy Laravel Website
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # Install dependencies via Composer
      - name: 📦 Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-dev --optimize-autoloader

      # Sync files via FTP
      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}  # FTP server address, e.g. ftp.wabiltz.com
          username: ${{ secrets.FTP_USERNAME }}  # FTP username
          password: ${{ secrets.FTP_PASSWORD }}  # FTP password
          local-dir: ./  # Local directory to deploy (root of your repository)
          server-dir: /home/wablitzc/public_html/wablitz.com  # Target directory on your server
          exclude: |
            .git*
            node_modules
            vendor
            .github

      # Copy .env.example to .env
      - name: 📄 Copy .env.example to .env
        run: |
          cp .env.example .env

      # Set permissions to storage and bootstrap/cache directories
      - name: 🛠 Set Permissions for Laravel Directories
        run: |
          sshpass -p ${{ secrets.FTP_PASSWORD }} ssh ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }} "chmod -R 777 /home/wablitzc/public_html/wablitz.com/storage /home/wablitzc/public_html/wablitz.com/bootstrap/cache"

      # Clear Laravel cache after deployment
      - name: 🧹 Clear Laravel cache
        run: |
          sshpass -p ${{ secrets.FTP_PASSWORD }} ssh ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }} "cd /home/wablitzc/public_html/wablitz.com && php artisan config:cache && php artisan route:cache && php artisan view:cache"
