name: 🚀 Deploy to cPanel via FTP (Passive Mode)
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy Laravel Website
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        
      - name: 📦 Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          
      - name: 📦 Zip vendor folder
        run: |
          zip -r vendor.zip vendor
          rm -rf vendor
          
      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
          protocol: ftp
          port: 21  # Default FTP port
          passive: true  # Use passive mode
          exclude: |
            .git*
            node_modules
            .github
