name: 🚀 Deploy Laravel ke wablitz.com

on:
  push:
    branches:
      - main
  workflow_dispatch:    # Memungkinkan untuk menjalankan workflow secara manual

jobs:
  web-deploy:
    name: 🎉 Deploy Website
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      
    - name: 🧹 Prepare files
      run: |
        # Hapus direktori dan file yang tidak perlu di-upload
        rm -rf vendor
        rm -rf node_modules
        rm -rf .git
        rm -rf .github
        
        # Buat file deploy-script.php untuk instalasi di server
        echo "<?php
        // Script untuk menjalankan perintah setelah deployment
        shell_exec('composer install --no-dev --optimize-autoloader --no-interaction');
        shell_exec('cp .env.example .env');
        shell_exec('php artisan key:generate');
        shell_exec('php artisan config:clear');
        shell_exec('php artisan cache:clear');
        shell_exec('chmod -R 755 storage bootstrap/cache');
        echo 'Deployment berhasil! Dependencies sudah terinstall.';
        " > deploy-script.php
    
    - name: 📂 Deploy ke Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.wablitz.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/sajadav2testing/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
          **/storage/framework/cache/**
          **/storage/framework/sessions/**
          **/storage/framework/views/**
          **/storage/logs/**
